### ISSUE TITLE
Can't build without OpenSSL

### ISSUE THREAD

**Issue by SoniEx2** [ikatson/rqbit#1] opened 2021-09-29 21:50 UTC
It doesn't seem to be possible to build without OpenSSL. `cargo build --no-default-features --features sha1-rust` doesn't seem to get rid of the OpenSSL dependency.

**Comment by ikatson** [comment] 2021-09-29 23:08
Just commited https://github.com/ikatson/rqbit/commit/f40a2274597d4f5e3bfa2566a77cad9886fd7db5 which should help (if it works as intended).

First of all, as the code layout is a workspace, it's probably affected by https://github.com/rust-lang/cargo/issues/7039. I did not check though, they suggest some nightly compiler flag to make it work in a workspace.

But with the commit above what you can try is:

    cd crates/rqbit/
    cargo build --release --no-default-features --features sha1-rust

    #get the binary from ./crates/rqbit/target/release vs the default ./target/release

**Comment by SoniEx2** [comment] 2021-09-30 00:24
Hmm, nope, no luck.

Commenting out all the default features makes it work but ah well. :/

**Comment by SoniEx2** [comment] 2021-09-30 00:26
This seems to be more relevant: https://github.com/rust-lang/cargo/issues/4463

**Comment by ikatson** [comment] 2021-09-30 08:04
Did another try in https://github.com/ikatson/rqbit/commit/1bcc16c327c41d1ac6f4811951cdac2da483104f. Workspaces + dependencies seems to be a bit messed up yeah. Can you check if this works for you now?

```
cd crates/rqbit/
cargo build --release --no-default-features --features sha1-rust

#get the binary from ./crates/rqbit/target/release vs the default ./target/release
```

**Comment by SoniEx2** [comment] 2021-09-30 10:25
Hmm, still doesn't work.

Ah well, don't worry about it, it's not like mio supports wasm32-unknown-emscripten either, so it's not like this is gonna go anywhere anytime soon. :/

**Comment by ikatson** [comment] 2021-09-30 17:48
Alright, thanks for trying the fixes, I'll close it then, if someone cares about it enough feel free to reopen

**Closed** 2021-09-30 17:49 UTC

**Comment by ikatson** [comment] 2021-10-17 17:20
@SoniEx2 I figured out what the problem here was - I guess you were building for linux, and on linux openssl was transitively required for another dependency.

This should work on linux with the latest changes:

    cargo build --release --no-default-features --features=sha1-rust,rust-tls

I also made a Makefile rule to cross-compile for linux, and it certainly builds without openssl, here's how I do that on mac

```
export CC_x86_64_unknown_linux_gnu=x86_64-unknown-linux-gnu-gcc && \
export CXX_x86_64_unknown_linux_gnu=x86_64-unknown-linux-gnu-g++ && \
export AR_x86_64_unknown_linux_gnu=x86_64-unknown-linux-gnu-ar && \
export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc && \
cargo build --release --target=x86_64-unknown-linux-gnu --no-default-features \
    --features=sha1-rust,rust-tls
```
